### ISSUE TITLE
add offset for iphone 5s

### ISSUE THREAD

**Issue by sathish2k** [MTJailed/jailbreakme#4]
//iphone 5S
    offsets["iPhone 5S"][11.31] = {
        padding: 0x18,
        vtable: 0,
        disableprimitivegigacage: 0x18851a7d4,
        callbacks: 0x1b3199698,
        g_gigacagebaseptrs: 0x1b1bec000,
        g_typedarraypoisons: 0x1b3199720,
        longjmp: 0x180b12778,
        dlsym: 0x18084ef90,
        startfixedmempool: 0x1b31990b8,
        endfixedmempool: 0x1b31990c0,
        jit_writeseperateheaps_func: 0x1b31990c8,
        usefastpermissions_jitcopy: 0x1b1be8018,
        ptr_stack_check_guard: 0x1b30f1ef8,
        modelio_popx8: 0,
        coreaudio_popx2: 0,
        linkcode_gadget: 0
    };
offsets["iPhone 5S"][11.3] = offsets["iPhone 5S"][11.31];

**Comment by sathish2k** [comment]
![whatsapp image 2018-06-25 at 11 14 35 am](https://user-images.githubusercontent.com/21261944/41832387-7585f3a4-7869-11e8-84d8-03a967cc972e.jpeg)

**Comment by MTJailed** [comment]
Thank you. They are added now with only the ROP-gadgets missing ;)
